<?php
return [ 
    'WEB_PORTAL'=>1,
    'Arival_cancel_success'=>'Arrival Cancelled Successfully',
    'Arival_cancel_error' =>'Error in Cancelling Arrival',
    'FLASH_NOT_ALLOW_FOR_DEMO'=>'Request not allow for demo version',
    'FLASH_CONNECTION'=>'Please check your internet connection and try again. ',
    'FLASH_SUCCESS_LOGIN_ALERT'=>'You`r not logged in.Please login and try again !',
    'FLASH_SUCCESS_LOGIN'=>'Successfully logged in !',
    'FLASH_SUCCESS_LOGOUT'=>'Successfully logged out !',
    'FLASH_INVALID_CREDENTIAL'=>'Invalid login credentials.',
    'FLASH_INVALID_EMAIL_ADDRESS'=>'Email address invalid!',
    'FLASH_EMAIL_VERIFY_1'=>'Your email address verified successfully ! ',
    'FLASH_EMAIL_VERIFY_0'=>'Your email address ##EMAIL## not verified.Try again! ',
    'FLASH_EMAIL_ADDRESS_EXIST'=>'Email address already exist.',
    'FLASH_MOBILE_NUMBER_EXIST'=>'Mobile number already exist.',
    'FLASH_ACC_CREATE_1'=>'Your account created successfully.',
    'FLASH_RESET_PASS_SUCCESS'=>'Your password successfully changed ! Login to continue!',
    'FLASH_RESET_PASS_FAIL'=>'404 Not Found or Reset password link expired !',
    'FLASH_ALL_FIELD_REQUIRED'=>'All Fields are required !',
    'FLASH_NPASS_CPASS_NOT_MATCH'=>'New password or Confirm password does not matched !',
    'FLASH_CPASS_LENGTH'=>"Password Must be 6 Character Long !",   
    'FLASH_REC_ADD_1'=>'Record successfully added!',
    'FLASH_REC_ADD_0'=>'Record not added.Try again!',
    'FLASH_REC_UPDATE_1'=>'Record successfully updated!', 
    'FLASH_REC_UPDATE_0'=>'Record not updated.Try again!',
    'FLASH_REC_DELETE_1'=>'Record successfully deleted!',
    'FLASH_REC_DELETE_0'=>'Record not deleted.Try again!',
    'FLASH_REC_REMOVE_1'=>'Record successfully removed!',
    'FLASH_REC_REMOVE_0'=>'Record not removed.Try again!',
    'FLASH_REC_NOT_FOUND'=>'Record not found.',
    'FLASH_CHECKOUT_1'=>'Checkout successfully',
    'FLASH_CHECKOUT_0'=>'Checkout failed.Try again',
    'FLASH_PROFILE_UPDATE_1'=>'Profile updated successfully!',    
    'FLASH_INVALID_PARAMS'=>'Invalid Parameters.Try Again.',
    'FLASH_NOT_ALLOW_URL'=>'Sorry ! You are not allowed request this url.',
    'FLASH_PAGE_NOT_ALLOWD'=>'You do not have authorization for this section.',
    'FLASH_DB_CONNECT_1'=>'Database connection successfully',
    'FLASH_DB_CONNECT_0'=>'Could not connect to the database. Please check your configuration.',

    'OTP_LIMIT'=>'30',
    'CACHING_TIME'=>'1',
    'REC_DAYS'=>10,
    'DEFAULT_LANG'=>'en', //for front site
    'LANG_LIST'=>[
        'en' => 'English',
        //'fr' => 'French',
        //'de' => 'German',
        'hi' => 'Hindi',
        //'rm' => 'Romansh',
        //'es' => 'Spanish, Castilian',
    ],
    'REASON'=>[
         'Personal'=>'Personal',
         'Professional'=>'Professional'
    ],
    'LIST_MAINTINANCE' =>[
              0=>'No',
              1=>'Yes',

    ],
    'GENDER'=>[
        'Male'=>'Male',
        'Female'=>'Female',
        'Other'=>'Other',
    ],
    'TYPES_OF_ID'=>[
        1=>'Aadhar Card',
        2=>'Driving License',
        3=>'Passport',
        4=>'Voter Id',
    ], 
    'STATUS_LIST'=>[
        1=>'Active',
        0=>'Inactive',
    ],
    'MEASURMENT_LIST'=>[
        1=>'Gm',
        2=>'Kg',
        3=>'Item',
        4=>'Piece',
        5=>'Set',
        6=>'Bottles',
        7=>'Cartoons',
    ],
   'ROOM_FLOOR'=>[
        1=>'Ground Floor',
        2=>'First Floor',
        3=>'Second Floor',
        4=>'Third Floor',
        5=>'Forth Floor',
        6=>'Fifth Floor',
        7=>'Sixth Floor',
        8=>'Seventh Floor',
        9=>'Eight Floor',
        10=>'Ninth Floor',
        11=>'Tenth Floor',
    ],
    'REFERRED_BY'=>[
        'Self'=>'Self',
        'ThirdParty'=>'ThirdParty',
    ],
    'MEAL_PLAN'=>[
      'EP' =>'EP',
      'CP'=> 'CP',
      'MAP'=> 'MAP',
      'AP' => 'AP'
    ],
      'Time'=>[
      'Daily' =>'Daily',
       'Weekly'=>'Weekly',
      'Monthly'=> 'Monthly',
      'Yearly'=> 'Yearly',
    ],
    'REFERRED_BY_NAME' =>[
      "F9" =>"F9",
      "Management"=>"Management",
      "TA"=>"TA",
      "OTA" =>"OTA",
      "Corporate"=>"Corporate"
    ],
    'MONTH_LIST'=>[
        '1'=>'January','2'=>'February','3'=>'March','4'=>'April','5'=>'May','6'=>'June','7'=>'July','8'=>'August','9'=>'September','10'=>'October','11'=>'November','12'=>'December'
    ],
    'PAYMENT_MODES'=>[
      1=>'Cash',
      2=>'Debit-Credit Card',
      3=>'Google Pay',
      4=>'Paytm',
      5=>'PhonePe',
      6=>'UPI',
      7=>'Send Payment Link',
      8=>'Bill to Corporate',
      9=>'Prepaid by OTA',
      10=>'OYO BTC PAYMENT',
      11=>'OTA BTC PAYMENT',
      14=>'bitcoin',
      16=>'BOOKING BTC PAYMENT',
      17=>'GOMMT BTC PAYMENT',
      18=>'HAPPYEASYGO BTC',
      19=>'AGODA BTC PAYMENT',
      20=>'BREVISTAY BTC PAYMENT',
      21=>'BAG2BAG BTC PAYMENT',
      22=>'STAYUNCLE BTC PAYMENT',
      23=>'FAB BTC PAYMENT'
    ],
    'LIST_STATUS'=>[
      1=>'Active', 
      0=>'Inactive'
    ],
    'LIST_CATEGORY'=>[
      'veg'=>'Veg', 
      'nonveg'=>'Non-Veg',
      'egg'=>'Egg'
    ],
    'LIST_UNITS'=>[
      'PAC-PACKS'=>'PAC-PACKS',
      'SQF-SQUARE FEET'=>'SQF-SQUARE FEET', 
      'SQM-SQUARE METERS'=>'SQM-SQUARE METERS'
    ],
    'LIST_ORDER_TYPES'=>[
      'all'=>'All', 
      'roomOrders'=>'Room Orders',
      'tableOrders'=>'Table Orders'
    ],
    'NATIONALITY_LIST'=>[
      1 => "Afghan",
      2 => "Albanian",
      3 => "Algerian",
      4 => "American",
      5 => "Andorran",
      6 => "Angolan",
      7 => "Antigua`s",
      8 => "Argentinean",
      9 => "Armenian",
      10 => "Australian",
      11 => "Austrian",
      12 => "Azerbaijani",
      13 => "Bahamian",
      14 => "Bangladeshi",
      15 => "Barbadian",
      16 => "Barbudans",
      17 => "Batswana",
      18 => "Belarusian",
      19 => "Belgian",
      20 => "Belizean",
      21 => "Beninese",
      22 => "Bhutanese",
      23 => "Bolivian",
      24 => "Bosnian",
      25 => "Brazilian",
      26 => "British",
      27 => "Bruneian",
      28 => "Bulgarian",
      29 => "Burkinabe",
      30 => "Burmese",
      31 => "Burundian",
      32 => "Cambodian",
      33 => "Cameroonian",
      34 => "Canadian",
      35 => "Cape Verdean",
      36 => "Central African",
      37 => "Chadian",
      38 => "Chilean",
      39 => "Chinese",
      40 => "Colombian",
      41 => "Comoran",
      42 => "Congolese",
      43 => "Costa Rican",
      44 => "Croatian",
      45 => "Cuban",
      46 => "Cypriot",
      47 => "Czech",
      48 => "Danish",
      49 => "Djibouti",
      50 => "Dominican",
      51 => "Dutch",
      52 => "East Timorese",
      53 => "Ecuadorean",
      54 => "Egyptian",
      55 => "Emirati (UAE)",
      56 => "Equatorial Guinean",
      57 => "Eritrean",
      58 => "Estonian",
      59 => "Ethiopian",
      60 => "Fijian",
      61 => "Filipino",
      62 => "Finnish",
      63 => "French",
      64 => "Gabonese",
      65 => "Gambian",
      66 => "Georgian",
      67 => "German",
      68 => "Ghanaian",
      69 => "Greek",
      70 => "Grenadian",
      71 => "Guatemalan",
      72 => "Guinea-Bissauan",
      73 => "Guinean",
      74 => "Guyanese",
      75 => "Haitian",
      76 => "Herzegovinian",
      77 => "Honduran",
      78 => "Hungarian",
      79 => "I-Kiribati",
      80 => "Icelander",
      81 => "Indian",
      82 => "Indonesian",
      83 => "Iranian",
      84 => "Iraqi",
      85 => "Irish",
      86 => "Israeli",
      87 => "Italian",
      88 => "Ivorian",
      89 => "Jamaican",
      90 => "Japanese",
      91 => "Jordanian",
      92 => "Kazakhstani",
      93 => "Kenyan",
      94 => "Kittian and Nevisian",
      95 => "Kuwaiti",
      96 => "Kyrgyz",
      97 => "Laotian",
      98 => "Latvian",
      99 => "Lebanese",
      100 => "Liberian",
      101 => "Libyan",
      102 => "Liechtensteiner",
      103 => "Lithuanian",
      104 => "Luxembourger",
      105 => "Macedonian",
      106 => "Malagasy",
      107 => "Malawian",
      108 => "Malaysian",
      109 => "Maldivan",
      110 => "Malian",
      111 => "Maltese",
      112 => "Marshallese",
      113 => "Mauritanian",
      114 => "Mauritian",
      115 => "Mexican",
      116 => "Micronesian",
      117 => "Moldovan",
      118 => "Monacan",
      119 => "Mongolian",
      120 => "Moroccan",
      121 => "Mosotho",
      122 => "Motswana",
      123 => "Mozambican",
      124 => "Namibian",
      125 => "Nauruan",
      126 => "Nepalese",
      127 => "New Zealander",
      128 => "Nicaraguan",
      129 => "Nigerian",
      130 => "Nigerien",
      131 => "North Korean",
      132 => "Northern Irish",
      133 => "Norwegian",
      134 => "Omani",
      135 => "Pakistani",
      136 => "Palestinian",
      137 => "Panamanian",
      138 => "Papua New Guinean",
      139 => "Paraguayan",
      140 => "Peruvian",
      141 => "Polish",
      142 => "Portuguese",
      143 => "Qatari",
      144 => "Romanian",
      145 => "Russian",
      146 => "Rwandan",
      147 => "Saint Lucian",
      148 => "Salvadoran",
      149 => "Samoan",
      150 => "San Marinese",
      151 => "Sao Tomean",
      152 => "Saudi Arabian",
      153 => "Scottish",
      154 => "Senegalese",
      155 => "Serbian",
      156 => "Seychellois",
      157 => "Sierra Leonean",
      158 => "Singaporean",
      159 => "Slovakian",
      160 => "Slovenian",
      161 => "Solomon Islander",
      162 => "Somali",
      163 => "South African",
      164 => "South Korean",
      165 => "Spanish",
      166 => "Sri Lankan",
      167 => "Sudanese",
      168 => "Surinamer",
      169 => "Swazi",
      170 => "Swedish",
      171 => "Swiss",
      172 => "Syrian",
      173 => "Taiwanese",
      174 => "Tajik",
      175 => "Tanzanian",
      176 => "Thai",
      177 => "Togolese",
      178 => "Tongan",
      179 => "Trinidadian/Tobagonian",
      180 => "Tunisia",
      181 => "Turkish",
      182 => "Tuvaluan",
      183 => "Ugandan",
      184 => "Ukrainian",
      185 => "Uruguayan",
      186 => "Uzbekistani",
      187 => "Venezuelan",
      188 => "Vietnamese",
      189 => "Welsh",
      190 => "Yemenite",
      191 => "Zambian",
      192 => "Zimbabwean",
    ],

    'COUNTRY_LIST'=>[
      [ 'code' => 'US', 'name' => 'United States'],
      [ 'code' => 'CA', 'name' => 'Canada'],
      [ 'code' => 'AU', 'name' => 'Australia'],
      [ 'code' => 'FR', 'name' => 'France'],
      [ 'code' => 'DE', 'name' => 'Germany'],
      [ 'code' => 'IS', 'name' => 'Iceland'],
      [ 'code' => 'IE', 'name' => 'Ireland'],
      [ 'code' => 'IT', 'name' => 'Italy'],
      [ 'code' => 'ES', 'name' => 'Spain'],
      [ 'code' => 'SE', 'name' => 'Sweden'],
      [ 'code' => 'AT', 'name' => 'Austria'],
      [ 'code' => 'BE', 'name' => 'Belgium'],
      [ 'code' => 'FI', 'name' => 'Finland'],
      [ 'code' => 'CZ', 'name' => 'Czech Republic'],
      [ 'code' => 'DK', 'name' => 'Denmark'],
      [ 'code' => 'NO', 'name' => 'Norway'],
      [ 'code' => 'GB', 'name' => 'United Kingdom'],
      [ 'code' => 'CH', 'name' => 'Switzerland'],
      [ 'code' => 'NZ', 'name' => 'New Zealand'],
      [ 'code' => 'RU', 'name' => 'Russian Federation'],
      [ 'code' => 'PT', 'name' => 'Portugal'],
      [ 'code' => 'NL', 'name' => 'Netherlands'],
      [ 'code' => 'IM', 'name' => 'Isle of Man'],
      [ 'code' => 'AF', 'name' => 'Afghanistan'],
      [ 'code' => 'AX', 'name' => 'Aland Islands '],
      [ 'code' => 'AL', 'name' => 'Albania'],
      [ 'code' => 'DZ', 'name' => 'Algeria'],
      [ 'code' => 'AS', 'name' => 'American Samoa'],
      [ 'code' => 'AD', 'name' => 'Andorra'],
      [ 'code' => 'AO', 'name' => 'Angola'],
      [ 'code' => 'AI', 'name' => 'Anguilla'],
      [ 'code' => 'AQ', 'name' => 'Antarctica'],
      [ 'code' => 'AG', 'name' => 'Antigua and Barbuda'],
      [ 'code' => 'AR', 'name' => 'Argentina'],
      [ 'code' => 'AM', 'name' => 'Armenia'],
      [ 'code' => 'AW', 'name' => 'Aruba'],
      [ 'code' => 'AZ', 'name' => 'Azerbaijan'],
      [ 'code' => 'BS', 'name' => 'Bahamas'],
      [ 'code' => 'BH', 'name' => 'Bahrain'],
      [ 'code' => 'BD', 'name' => 'Bangladesh'],
      [ 'code' => 'BB', 'name' => 'Barbados'],
      [ 'code' => 'BY', 'name' => 'Belarus'],
      [ 'code' => 'BZ', 'name' => 'Belize'],
      [ 'code' => 'BJ', 'name' => 'Benin'],
      [ 'code' => 'BM', 'name' => 'Bermuda'],
      [ 'code' => 'BT', 'name' => 'Bhutan'],
      [ 'code' => 'BO', 'name' => 'Bolivia, Plurinational State of'],
      [ 'code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba'],
      [ 'code' => 'BA', 'name' => 'Bosnia and Herzegovina'],
      [ 'code' => 'BW', 'name' => 'Botswana'],
      [ 'code' => 'BV', 'name' => 'Bouvet Island'],
      [ 'code' => 'BR', 'name' => 'Brazil'],
      [ 'code' => 'IO', 'name' => 'British Indian Ocean Territory'],
      [ 'code' => 'BN', 'name' => 'Brunei Darussalam'],
      [ 'code' => 'BG', 'name' => 'Bulgaria'],
      [ 'code' => 'BF', 'name' => 'Burkina Faso'],
      [ 'code' => 'BI', 'name' => 'Burundi'],
      [ 'code' => 'KH', 'name' => 'Cambodia'],
      [ 'code' => 'CM', 'name' => 'Cameroon'],
      [ 'code' => 'CV', 'name' => 'Cape Verde'],
      [ 'code' => 'KY', 'name' => 'Cayman Islands'],
      [ 'code' => 'CF', 'name' => 'Central African Republic'],
      [ 'code' => 'TD', 'name' => 'Chad'],
      [ 'code' => 'CL', 'name' => 'Chile'],
      [ 'code' => 'CN', 'name' => 'China'],
      [ 'code' => 'CX', 'name' => 'Christmas Island'],
      [ 'code' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
      [ 'code' => 'CO', 'name' => 'Colombia'],
      [ 'code' => 'KM', 'name' => 'Comoros'],
      [ 'code' => 'CG', 'name' => 'Congo'],
      [ 'code' => 'CD', 'name' => 'Congo, the Democratic Republic of the'],
      [ 'code' => 'CK', 'name' => 'Cook Islands'],
      [ 'code' => 'CR', 'name' => 'Costa Rica'],
      [ 'code' => 'CI', 'name' => 'Cote d\'Ivoire'],
      [ 'code' => 'HR', 'name' => 'Croatia'],
      [ 'code' => 'CU', 'name' => 'Cuba'],
      [ 'code' => 'CW', 'name' => 'Curaçao'],
      [ 'code' => 'CY', 'name' => 'Cyprus'],
      [ 'code' => 'DJ', 'name' => 'Djibouti'],
      [ 'code' => 'DM', 'name' => 'Dominica'],
      [ 'code' => 'DO', 'name' => 'Dominican Republic'],
      [ 'code' => 'EC', 'name' => 'Ecuador'],
      [ 'code' => 'EG', 'name' => 'Egypt'],
      [ 'code' => 'SV', 'name' => 'El Salvador'],
      [ 'code' => 'GQ', 'name' => 'Equatorial Guinea'],
      [ 'code' => 'ER', 'name' => 'Eritrea'],
      [ 'code' => 'EE', 'name' => 'Estonia'],
      [ 'code' => 'ET', 'name' => 'Ethiopia'],
      [ 'code' => 'FK', 'name' => 'Falkland Islands (Malvinas)'],
      [ 'code' => 'FO', 'name' => 'Faroe Islands'],
      [ 'code' => 'FJ', 'name' => 'Fiji'],
      [ 'code' => 'GF', 'name' => 'French Guiana'],
      [ 'code' => 'PF', 'name' => 'French Polynesia'],
      [ 'code' => 'TF', 'name' => 'French Southern Territories'],
      [ 'code' => 'GA', 'name' => 'Gabon'],
      [ 'code' => 'GM', 'name' => 'Gambia'],
      [ 'code' => 'GE', 'name' => 'Georgia'],
      [ 'code' => 'GH', 'name' => 'Ghana'],
      [ 'code' => 'GI', 'name' => 'Gibraltar'],
      [ 'code' => 'GR', 'name' => 'Greece'],
      [ 'code' => 'GL', 'name' => 'Greenland'],
      [ 'code' => 'GD', 'name' => 'Grenada'],
      [ 'code' => 'GP', 'name' => 'Guadeloupe'],
      [ 'code' => 'GU', 'name' => 'Guam'],
      [ 'code' => 'GT', 'name' => 'Guatemala'],
      [ 'code' => 'GG', 'name' => 'Guernsey'],
      [ 'code' => 'GN', 'name' => 'Guinea'],
      [ 'code' => 'GW', 'name' => 'Guinea-Bissau'],
      [ 'code' => 'GY', 'name' => 'Guyana'],
      [ 'code' => 'HT', 'name' => 'Haiti'],
      [ 'code' => 'HM', 'name' => 'Heard Island and McDonald Islands'],
      [ 'code' => 'VA', 'name' => 'Holy See (Vatican City State)'],
      [ 'code' => 'HN', 'name' => 'Honduras'],
      [ 'code' => 'HK', 'name' => 'Hong Kong'],
      [ 'code' => 'HU', 'name' => 'Hungary'],
      [ 'code' => 'IN', 'name' => 'India'],
      [ 'code' => 'ID', 'name' => 'Indonesia'],
      [ 'code' => 'IR', 'name' => 'Iran, Islamic Republic of'],
      [ 'code' => 'IQ', 'name' => 'Iraq'],
      [ 'code' => 'IL', 'name' => 'Israel'],
      [ 'code' => 'JM', 'name' => 'Jamaica'],
      [ 'code' => 'JP', 'name' => 'Japan'],
      [ 'code' => 'JE', 'name' => 'Jersey'],
      [ 'code' => 'JO', 'name' => 'Jordan'],
      [ 'code' => 'KZ', 'name' => 'Kazakhstan'],
      [ 'code' => 'KE', 'name' => 'Kenya'],
      [ 'code' => 'KI', 'name' => 'Kiribati'],
      [ 'code' => 'KP', 'name' => 'Korea, Democratic People`s Republic of'],
      [ 'code' => 'KR', 'name' => 'Korea, Republic of'],
      [ 'code' => 'KW', 'name' => 'Kuwait'],
      [ 'code' => 'KG', 'name' => 'Kyrgyzstan'],
      [ 'code' => 'LA', 'name' => 'Lao People\'s Democratic Republic'],
      [ 'code' => 'LV', 'name' => 'Latvia'],
      [ 'code' => 'LB', 'name' => 'Lebanon'],
      [ 'code' => 'LS', 'name' => 'Lesotho'],
      [ 'code' => 'LR', 'name' => 'Liberia'],
      [ 'code' => 'LY', 'name' => 'Libyan Arab Jamahiriya'],
      [ 'code' => 'LI', 'name' => 'Liechtenstein'],
      [ 'code' => 'LT', 'name' => 'Lithuania'],
      [ 'code' => 'LU', 'name' => 'Luxembourg'],
      [ 'code' => 'MO', 'name' => 'Macao'],
      [ 'code' => 'MK', 'name' => 'Macedonia'],
      [ 'code' => 'MG', 'name' => 'Madagascar'],
      [ 'code' => 'MW', 'name' => 'Malawi'],
      [ 'code' => 'MY', 'name' => 'Malaysia'],
      [ 'code' => 'MV', 'name' => 'Maldives'],
      [ 'code' => 'ML', 'name' => 'Mali'],
      [ 'code' => 'MT', 'name' => 'Malta'],
      [ 'code' => 'MH', 'name' => 'Marshall Islands'],
      [ 'code' => 'MQ', 'name' => 'Martinique'],
      [ 'code' => 'MR', 'name' => 'Mauritania'],
      [ 'code' => 'MU', 'name' => 'Mauritius'],
      [ 'code' => 'YT', 'name' => 'Mayotte'],
      [ 'code' => 'MX', 'name' => 'Mexico'],
      [ 'code' => 'FM', 'name' => 'Micronesia, Federated States of'],
      [ 'code' => 'MD', 'name' => 'Moldova, Republic of'],
      [ 'code' => 'MC', 'name' => 'Monaco'],
      [ 'code' => 'MN', 'name' => 'Mongolia'],
      [ 'code' => 'ME', 'name' => 'Montenegro'],
      [ 'code' => 'MS', 'name' => 'Montserrat'],
      [ 'code' => 'MA', 'name' => 'Morocco'],
      [ 'code' => 'MZ', 'name' => 'Mozambique'],
      [ 'code' => 'MM', 'name' => 'Myanmar'],
      [ 'code' => 'NA', 'name' => 'Namibia'],
      [ 'code' => 'NR', 'name' => 'Nauru'],
      [ 'code' => 'NP', 'name' => 'Nepal'],
      [ 'code' => 'NC', 'name' => 'New Caledonia'],
      [ 'code' => 'NI', 'name' => 'Nicaragua'],
      [ 'code' => 'NE', 'name' => 'Niger'],
      [ 'code' => 'NG', 'name' => 'Nigeria'],
      [ 'code' => 'NU', 'name' => 'Niue'],
      [ 'code' => 'NF', 'name' => 'Norfolk Island'],
      [ 'code' => 'MP', 'name' => 'Northern Mariana Islands'],
      [ 'code' => 'OM', 'name' => 'Oman'],
      [ 'code' => 'PK', 'name' => 'Pakistan'],
      [ 'code' => 'PW', 'name' => 'Palau'],
      [ 'code' => 'PS', 'name' => 'Palestinian Territory, Occupied'],
      [ 'code' => 'PA', 'name' => 'Panama'],
      [ 'code' => 'PG', 'name' => 'Papua New Guinea'],
      [ 'code' => 'PY', 'name' => 'Paraguay'],
      [ 'code' => 'PE', 'name' => 'Peru'],
      [ 'code' => 'PH', 'name' => 'Philippines'],
      [ 'code' => 'PN', 'name' => 'Pitcairn'],
      [ 'code' => 'PL', 'name' => 'Poland'],
      [ 'code' => 'PR', 'name' => 'Puerto Rico'],
      [ 'code' => 'QA', 'name' => 'Qatar'],
      [ 'code' => 'RE', 'name' => 'Reunion'],
      [ 'code' => 'RO', 'name' => 'Romania'],
      [ 'code' => 'RW', 'name' => 'Rwanda'],
      [ 'code' => 'BL', 'name' => 'Saint Barthélemy'],
      [ 'code' => 'SH', 'name' => 'Saint Helena'],
      [ 'code' => 'KN', 'name' => 'Saint Kitts and Nevis'],
      [ 'code' => 'LC', 'name' => 'Saint Lucia'],
      [ 'code' => 'MF', 'name' => 'Saint Martin (French part)'],
      [ 'code' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
      [ 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
      [ 'code' => 'WS', 'name' => 'Samoa'],
      [ 'code' => 'SM', 'name' => 'San Marino'],
      [ 'code' => 'ST', 'name' => 'Sao Tome and Principe'],
      [ 'code' => 'SA', 'name' => 'Saudi Arabia'],
      [ 'code' => 'SN', 'name' => 'Senegal'],
      [ 'code' => 'RS', 'name' => 'Serbia'],
      [ 'code' => 'SC', 'name' => 'Seychelles'],
      [ 'code' => 'SL', 'name' => 'Sierra Leone'],
      [ 'code' => 'SG', 'name' => 'Singapore'],
      [ 'code' => 'SX', 'name' => 'Sint Maarten (Dutch part)'],
      [ 'code' => 'SK', 'name' => 'Slovakia'],
      [ 'code' => 'SI', 'name' => 'Slovenia'],
      [ 'code' => 'SB', 'name' => 'Solomon Islands'],
      [ 'code' => 'SO', 'name' => 'Somalia'],
      [ 'code' => 'ZA', 'name' => 'South Africa'],
      [ 'code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands'],
      [ 'code' => 'LK', 'name' => 'Sri Lanka'],
      [ 'code' => 'SD', 'name' => 'Sudan'],
      [ 'code' => 'SR', 'name' => 'Suriname'],
      [ 'code' => 'SJ', 'name' => 'Svalbard and Jan Mayen'],
      [ 'code' => 'SZ', 'name' => 'Swaziland'],
      [ 'code' => 'SY', 'name' => 'Syrian Arab Republic'],
      [ 'code' => 'TW', 'name' => 'Taiwan, Province of China'],
      [ 'code' => 'TJ', 'name' => 'Tajikistan'],
      [ 'code' => 'TZ', 'name' => 'Tanzania, United Republic of'],
      [ 'code' => 'TH', 'name' => 'Thailand'],
      [ 'code' => 'TL', 'name' => 'Timor-Leste'],
      [ 'code' => 'TG', 'name' => 'Togo'],
      [ 'code' => 'TK', 'name' => 'Tokelau'],
      [ 'code' => 'TO', 'name' => 'Tonga'],
      [ 'code' => 'TT', 'name' => 'Trinidad and Tobago'],
      [ 'code' => 'TN', 'name' => 'Tunisia'],
      [ 'code' => 'TR', 'name' => 'Turkey'],
      [ 'code' => 'TM', 'name' => 'Turkmenistan'],
      [ 'code' => 'TC', 'name' => 'Turks and Caicos Islands'],
      [ 'code' => 'TV', 'name' => 'Tuvalu'],
      [ 'code' => 'UG', 'name' => 'Uganda'],
      [ 'code' => 'UA', 'name' => 'Ukraine'],
      [ 'code' => 'AE', 'name' => 'United Arab Emirates'],
      [ 'code' => 'UM', 'name' => 'United States Minor Outlying Islands'],
      [ 'code' => 'UY', 'name' => 'Uruguay'],
      [ 'code' => 'UZ', 'name' => 'Uzbekistan'],
      [ 'code' => 'VU', 'name' => 'Vanuatu'],
      [ 'code' => 'VE', 'name' => 'Venezuela, Bolivarian Republic of'],
      [ 'code' => 'VN', 'name' => 'Viet Nam'],
      [ 'code' => 'VG', 'name' => 'Virgin Islands, British'],
      [ 'code' => 'VI', 'name' => 'Virgin Islands, U.S.'],
      [ 'code' => 'WF', 'name' => 'Wallis and Futuna'],
      [ 'code' => 'EH', 'name' => 'Western Sahara'],
      [ 'code' => 'YE', 'name' => 'Yemen'],
      [ 'code' => 'ZM', 'name' => 'Zambia'],
      [ 'code' => 'ZW', 'name' => 'Zimbabwe']
    ],
];


