<?php
/*
[
    'en' => 'English',
    'fr' => 'French',
    'hi' => 'Hindi',
    'rm' => 'Romansh',
    'es' => 'Spanish, Castile`s',
]
*/
return [
    /* ----- side menu ----- */
        'sidemenu_dashboard'=>[
            'en'=>'Dashboard',
            'fr'=>'',
            'hi'=>'डैशबोर्ड',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_housekeeping'=>[
            'en'=>'HouseKeeping',
            'fr'=>'',
            'hi'=>'डैशबोर्ड',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_arrival'=>[
            'en'=>'Arrival',
            'fr'=>'',
            'hi'=>'चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_arrival_add'=>[
            'en'=>'Add Arrival',
            'fr'=>'',
            'hi'=>'चेक-इन जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_arrival_all'=>[
            'en'=>'Arrivals List',
            'fr'=>'',
            'hi'=>'सभी चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_arrival_checkout_all'=>[
            'en'=>'All Arrival Check Out`s',
            'fr'=>'',
            'hi'=>'सभी चेक आउट',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_checkin'=>[
            'en'=>'Check In',
            'fr'=>'',
            'hi'=>'चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_checkin_add'=>[
            'en'=>'Add Check In',
            'fr'=>'',
            'hi'=>'चेक-इन जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_checkin_all'=>[
            'en'=>'All Check In`s',
            'fr'=>'',
            'hi'=>'सभी चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_single_checkin'=>[
            'en'=>'Single Check In`s',
            'fr'=>'',
            'hi'=>'सिंगल चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_multi_checkin'=>[
            'en'=>'Multiple Check In`s',
            'fr'=>'',
            'hi'=>'एकाधिक चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_checkout_all'=>[
            'en'=>'All Check Out`s',
            'fr'=>'',
            'hi'=>'सभी चेक आउट',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_users'=>[
            'en'=>'Users',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_user_add'=>[
            'en'=>'Add User',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_user_all'=>[
            'en'=>'All Users',
            'fr'=>'',
            'hi'=>'सभी उपयोगकर्ताओं',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_corporate'=>[
            'en'=>'Corporate \ TA \ OTA',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_corporate_add'=>[
            'en'=>'Add Corporate',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_corporate_all'=>[
            'en'=>'All Corporates',
            'fr'=>'',
            'hi'=>'सभी उपयोगकर्ताओं',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_ta_add'=>[
            'en'=>'Add TA',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_ota_add'=>[
            'en'=>'Add OTA',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_ota_all'=>[
            'en'=>'All OTAs',
            'fr'=>'',
            'hi'=>'सभी उपयोगकर्ताओं',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_ta_all'=>[
            'en'=>'All TAs',
            'fr'=>'',
            'hi'=>'सभी उपयोगकर्ताओं',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_customers'=>[
            'en'=>'Customers',
            'fr'=>'',
            'hi'=>'ग्राहक',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_customer_add'=>[
            'en'=>'Add Customer',
            'fr'=>'',
            'hi'=>'ग्राहक जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_customer_all'=>[
            'en'=>'All Customers',
            'fr'=>'',
            'hi'=>'',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_fooditems'=>[
            'en'=>'Food Items',
            'fr'=>'',
            'hi'=>'खाद्य - सामग्री',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_foodcat_add'=>[
            'en'=>'Add Food Category',
            'fr'=>'',
            'hi'=>'खाद्य श्रेणी जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_foodcat_all'=>[
            'en'=>'All FoodCategory',
            'fr'=>'',
            'hi'=>'सभी खाद्य श्रेणी',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_fooditem_add'=>[
            'en'=>'Add Food Item',
            'fr'=>'',
            'hi'=>'खाद्य पदार्थ जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_fooditem_all'=>[
            'en'=>'All Food Item',
            'fr'=>'',
            'hi'=>'सभी खाद्य पदार्थ',
            'rm'=>'',
            'es'=>'',
        ],

        'sidemenu_product_add'=>[
            'en'=>'Add Product',
            'fr'=>'',
            'hi'=>'उत्पाद जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_product_all'=>[
            'en'=>'All Products',
            'fr'=>'',
            'hi'=>'सारे उत्पाद',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_stocks'=>[
            'en'=>'Stocks',
            'fr'=>'',
            'hi'=>'स्टॉक्स',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_stock_add'=>[
            'en'=>'Add Stock',
            'fr'=>'',
            'hi'=>'स्टॉक जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_stock_history'=>[
            'en'=>'Stocks History',
            'fr'=>'',
            'hi'=>'स्टॉक्स इतिहास',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_roomtypes'=>[
            'en'=>'Room Types',
            'fr'=>'',
            'hi'=>'कक्ष के प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_roomtype_add'=>[
            'en'=>'Add Room Type',
            'fr'=>'',
            'hi'=>'कक्ष प्रकार जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_roomtype_all'=>[
            'en'=>'All Room Types',
            'fr'=>'',
            'hi'=>'सभी प्रकार के कक्ष',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_datepricerange_all'=>[
            'en'=>'All Date Price Range',
            'fr'=>'',
            'hi'=>'सभी दिनांक मूल्य सीमा',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_rooms'=>[
            'en'=>'Rooms',
            'fr'=>'',
            'hi'=>'कक्ष',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_room_add'=>[
            'en'=>'Add Room',
            'fr'=>'',
            'hi'=>'कक्ष जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_room_all'=>[
            'en'=>'All Rooms',
            'fr'=>'',
            'hi'=>'सभी कक्ष',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_amenities'=>[
            'en'=>'Amenities',
            'fr'=>'',
            'hi'=>'सुविधा',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_amenities_add'=>[
            'en'=>'Add Amenities',
            'fr'=>'',
            'hi'=>'सुविधा जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_amenities_all'=>[
            'en'=>'All Amenities',
            'fr'=>'',
            'hi'=>'सभी सुविधा',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_settings'=>[
            'en'=>'Settings',
            'fr'=>'',
            'hi'=>'सेटिंग्स',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_permissions'=>[
            'en'=>'Permissions',
            'fr'=>'',
            'hi'=>'अनुमतियां',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_expense'=>[
            'en'=>'Expense',
            'fr'=>'',
            'hi'=>'व्यय',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_expensecat_add'=>[
            'en'=>'Add Category',
            'fr'=>'',
            'hi'=>'श्रेणी जोड़े',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_expensecat_all'=>[
            'en'=>'All Category',
            'fr'=>'',
            'hi'=>'सभी श्रेणी',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_expense_add'=>[
            'en'=>'Add Expense',
            'fr'=>'',
            'hi'=>'व्यय जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_expense_all'=>[
            'en'=>'All Expense',
            'fr'=>'',
            'hi'=>'सभी व्यय',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_meal_master'=>[
            'en'=>'Meal Master',
            'fr'=>'',
            'hi'=>'भोजन मास्टर',
            'rm'=>'',
            'es'=>'',
        ],
    /* ----- /side menu ----- */

    /* ----- headings ----- */
        'heading_login'=>[
            'en'=>'Login',
            'fr'=>'',
            'hi'=>'लॉग इन',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_site_settings'=>[
            'en'=>'Site Settings',
            'fr'=>'',
            'hi'=>'साइट सेटिंग्स',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_gst_settings'=>[
            'en'=>'GST Settings',
            'fr'=>'',
            'hi'=>'जीएसटी सेटिंग्स',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_smsapi_settings'=>[
            'en'=>'SMS Api Settings',
            'fr'=>'',
            'hi'=>'एसएमएस एपीआई सेटिंग्स',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_currency_settings'=>[
            'en'=>'Currency Settings',
            'fr'=>'',
            'hi'=>'मुद्रा सेटिंग्स',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_default_settings'=>[
            'en'=>'Default Settings',
            'fr'=>'',
            'hi'=>'डिफ़ॉल्ट सेटिंग्स',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_food_category'=>[
            'en'=>'Food Category',
            'fr'=>'',
            'hi'=>'खाद्य श्रेणी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_food_category_list'=>[
            'en'=>'List Food Category',
            'fr'=>'',
            'hi'=>'सूची खाद्य श्रेणी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_food_item'=>[
            'en'=>'Food Item',
            'fr'=>'',
            'hi'=>'खाद्य - सामग्री',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_food_item_list'=>[
            'en'=>'List Food Items',
            'fr'=>'',
            'hi'=>'सूची खाद्य पदार्थ',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_expense_category'=>[
            'en'=>'Expense Category',
            'fr'=>'',
            'hi'=>'व्यय की श्रेणी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_expense_category_list'=>[
            'en'=>'List Expense Category',
            'fr'=>'',
            'hi'=>'सूची व्यय श्रेणी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_expense'=>[
            'en'=>'Expenses',
            'fr'=>'',
            'hi'=>'व्यय',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_filter_expense'=>[
            'en'=>'Filter Expense',
            'fr'=>'',
            'hi'=>'फ़िल्टर व्यय',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_expense_list'=>[
            'en'=>'List Expenses',
            'fr'=>'',
            'hi'=>'सूची व्यय',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_customer_info'=>[
            'en'=>'Customer Information',
            'fr'=>'',
            'hi'=>'ग्राहक सूचना',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_filter_orders'=>[
            'en'=>'Filter Orders',
            'fr'=>'',
            'hi'=>'फ़िल्टर ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_all_orders'=>[
            'en'=>'All Orders',
            'fr'=>'',
            'hi'=>'सभी ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_add_product'=>[
            'en'=>'Add Product',
            'fr'=>'',
            'hi'=>'उत्पाद जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_update_product'=>[
            'en'=>'Update Product',
            'fr'=>'',
            'hi'=>'अद्यतन उत्पाद',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_list_product'=>[
            'en'=>'List Products',
            'fr'=>'',
            'hi'=>'उत्पादों की सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_guest_type'=>[
            'en'=>'Guest Type',
            'fr'=>'',
            'hi'=>'अतिथि प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
         'heading_tax_type'=>[
            'en'=>'Select Tax Type',
            'fr'=>'',
            'hi'=>'अतिथि प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_existing_guest_list'=>[
            'en'=>'Existing Guest List',
            'fr'=>'',
            'hi'=>'मौजूदा अतिथि सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_guest_info'=>[
            'en'=>'Guest Information',
            'fr'=>'',
            'hi'=>'अतिथि जानकारी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_checkin_info'=>[
            'en'=>'Check In Information',
            'fr'=>'',
            'hi'=>'चेक-इन सूचना',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_idcard_info'=>[
            'en'=>'ID Card Information',
            'fr'=>'',
            'hi'=>'आईडी कार्ड की जानकारी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_person_info'=>[
            'en'=>'Information of Other Person',
            'fr'=>'',
            'hi'=>'अन्य व्यक्ति की जानकारी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_payment_info'=>[
            'en'=>'Payment Information',
            'fr'=>'',
            'hi'=>'भुगतान की जानकारी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_filter_checkouts'=>[
            'en'=>'Filter Checkouts',
            'fr'=>'',
            'hi'=>'फ़िल्टर चेकआउट',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_checkin_list'=>[
            'en'=>'Check In List',
            'fr'=>'',
            'hi'=>'चेक-इन सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_checkout_list'=>[
            'en'=>'Check Out List',
            'fr'=>'',
            'hi'=>'चेक-आउट सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_checkInOut_info'=>[
            'en'=>'Check In/Out Information',
            'fr'=>'',
            'hi'=>'चेक इन/आउट सूचना',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_additional_info'=>[
            'en'=>'Additional Information',
            'fr'=>'',
            'hi'=>'अतिरिक्त जानकारी',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_update_password'=>[
            'en'=>'Update Password',
            'fr'=>'',
            'hi'=>'पासवर्ड अपडेट करें',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_update_profile'=>[
            'en'=>'Update Profile',
            'fr'=>'',
            'hi'=>'प्रोफ़ाइल अपडेट करें',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_stock_history'=>[
            'en'=>'Stocks History',
            'fr'=>'',
            'hi'=>'स्टॉक्स इतिहास',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_filter_stock_history'=>[
            'en'=>'Filter Stocks History',
            'fr'=>'',
            'hi'=>'फ़िल्टर स्टॉक इतिहास',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_manage_inventory'=>[
            'en'=>'Manage Inventory',
            'fr'=>'',
            'hi'=>'इन्वेंटरी का प्रबंधन',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_term_and_conditions'=>[
            'en'=>'Term & Conditions',
            'fr'=>'',
            'hi'=>'नियम और शर्तें',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_list_roomtypes'=>[
            'en'=>'List Room Type',
            'fr'=>'',
            'hi'=>'सभी प्रकार के कमरे',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_list_datepricerange'=>[
            'en'=>'List Date Price Range',
            'fr'=>'',
            'hi'=>'सभी प्रकार के कमरे',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_list_datepricerange'=>[
            'en'=>'List Date Price Range',
            'fr'=>'',
            'hi'=>'सभी प्रकार के कमरे',
            'rm'=>'',
            'es'=>'',
        ],
        'sidemenu_mealplan_add'=>[
            'en'=>'Add Meal Plan ',
            'fr'=>'',
            'hi'=>'भोजन योजना जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
    /* ----- /headings ----- */

    /* ----- btns ----- */
        'btn_repeat_order'=>[
            'en'=>'Repeat Order',
            'fr'=>'',
            'hi'=>'दुबारा ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_view_order'=>[
            'en'=>'View Order',
            'fr'=>'',
            'hi'=>'ऑर्डर देखें',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_pay'=>[
            'en'=>'Pay',
            'fr'=>'',
            'hi'=>'वेतन',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_submit'=>[
            'en'=>'Submit',
            'fr'=>'',
            'hi'=>'प्रस्तुत',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_add'=>[
            'en'=>'Add',
            'fr'=>'',
            'hi'=>'जोड़ना',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_update'=>[
            'en'=>'Update',
            'fr'=>'',
            'hi'=>'अपडेट',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_save'=>[
            'en'=>'Save',
            'fr'=>'',
            'hi'=>'सहेजें',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_cancel'=>[
            'en'=>'Cancel',
            'fr'=>'',
            'hi'=>'रद्द',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_delete'=>[
            'en'=>'Delete',
            'fr'=>'',
            'hi'=>'हटाएं',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_reset'=>[
            'en'=>'Reset',
            'fr'=>'',
            'hi'=>'रीसेट',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_print'=>[
            'en'=>'Print',
            'fr'=>'',
            'hi'=>'छाप',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_go_back'=>[
            'en'=>'Go To Back',
            'fr'=>'',
            'hi'=>'वापस जाएं',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_login'=>[
            'en'=>'Log in',
            'fr'=>'',
            'hi'=>'लॉग इन',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_search'=>[
            'en'=>'Search',
            'fr'=>'',
            'hi'=>'खोज',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_export'=>[
            'en'=>'Export',
            'fr'=>'',
            'hi'=>'निर्यात',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_view_item'=>[
            'en'=>'View Items',
            'fr'=>'',
            'hi'=>'आइटम देखें',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_view'=>[
            'en'=>'View',
            'fr'=>'',
            'hi'=>'देखें',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_invoice_food'=>[
            'en'=>'Invoice Food',
            'fr'=>'',
            'hi'=>'रसीद खाना',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_invoice_room'=>[
            'en'=>'Invoice Room',
            'fr'=>'',
            'hi'=>'रसीद कक्ष',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_food_order'=>[
            'en'=>'Food Order',
            'fr'=>'',
            'hi'=>'खाद्य ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_checkout'=>[
            'en'=>'Check Out',
            'fr'=>'',
            'hi'=>'चेक आउट',
            'rm'=>'',
            'es'=>'',
        ],
        'btn_checkin_edit'=>[
            'en'=>'Edit',
            'fr'=>'',
            'hi'=>'चेक आउट',
            'rm'=>'',
            'es'=>'',
        ],
    /* ----- /btns ----- */

    /* ----- placeholder ----- */
        'ph_enter'=>[
            'en'=>'Enter ',
            'fr'=>'',
            'hi'=>'दर्ज',
            'rm'=>'',
            'es'=>'',
        ],
        'ph_select'=>[
            'en'=>'--Select--',
            'fr'=>'',
            'hi'=>'--चयन--',
            'rm'=>'',
            'es'=>'',
        ],
        'ph_qty'=>[
            'en'=>'Enter Qty',
            'fr'=>'',
            'hi'=>'मात्रा दर्ज करें',
            'rm'=>'',
            'es'=>'',
        ],
        'ph_date'=>[
            'en'=>'Select Date',
            'fr'=>'',
            'hi'=>'तारीख़ चुनें',
            'rm'=>'',
            'es'=>'',
        ],
        'ph_date_from'=>[
            'en'=>'Select Date From',
            'fr'=>'',
            'hi'=>'से दिनांक का चयन करें',
            'rm'=>'',
            'es'=>'',
        ],
        'ph_date_to'=>[
            'en'=>'Select Date To',
            'fr'=>'',
            'hi'=>'दिनांक का चयन करें',
            'rm'=>'',
            'es'=>'',
        ],
        'ph_day_night'=>[
            'en'=>'Enter Number of Days/Night',
            'fr'=>'',
            'hi'=>'दिन/रात की संख्या दर्ज करें',
            'rm'=>'',
            'es'=>'',
        ],
        'ph_any_discount'=>[
            'en'=>'Enter Any Discount',
            'fr'=>'',
            'hi'=>'कोई भी छूट दर्ज करें',
            'rm'=>'',
            'es'=>'',
        ],

    /* ----- /placeholder ----- */

    /* ----- txt ----- */
        'txt_welcome'=>[
            'en'=>'Welcome',
            'fr'=>'',
            'hi'=>'स्वागत',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_profile'=>[
            'en'=>'Profile',
            'fr'=>'',
            'hi'=>'प्रोफ़ाइल',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_logout'=>[
            'en'=>'Logout',
            'fr'=>'',
            'hi'=>'लॉग आउट',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_rights_res'=>[
            'en'=>'All Rights Reserved',
            'fr'=>'',
            'hi'=>'सभी अधिकार सुरक्षित',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_today_checkin'=>[
            'en'=>'Today Check In`s',
            'fr'=>'',
            'hi'=>'आज चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_meal_plan'=>[
            'en'=>'Meal Plan',
            'fr'=>'',
            'hi'=>'आज चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_corporate_ta'=>[
            'en'=>'Corporate/TA',
            'fr'=>'',
            'hi'=>'आज चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_today_arrivals'=>[
            'en'=>'Today Arrivals',
            'fr'=>'',
            'hi'=>'आज चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_today_checkout'=>[
            'en'=>'Today Check Out`s',
            'fr'=>'',
            'hi'=>'आज चेक आउट',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_today_orders'=>[
            'en'=>'Today Orders',
            'fr'=>'',
            'hi'=>'आज ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_add_new_orders'=>[
            'en'=>'Add New Order',
            'fr'=>'',
            'hi'=>'नया ऑर्डर जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_latest_orders'=>[
            'en'=>'Latest Orders',
            'fr'=>'',
            'hi'=>'नवीनतम ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_sno'=>[
            'en'=>'S.No',
            'fr'=>'',
            'hi'=>'',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_customer_name'=>[
            'en'=>'Customer Name',
            'fr'=>'',
            'hi'=>'ग्राहक का नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_customer_email'=>[
            'en'=>'Customer Email',
            'fr'=>'',
            'hi'=>'ग्राहक ईमेल',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_customer_mobile'=>[
            'en'=>'Customer Mobile',
            'fr'=>'',
            'hi'=>'ग्राहक मोबाइल',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_table_num'=>[
            'en'=>'Table No.',
            'fr'=>'',
            'hi'=>'तालिका संख्या',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_room_num'=>[
            'en'=>'Room No.',
            'fr'=>'',
            'hi'=>'कमरा क्रमांक।',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_order_amount'=>[
            'en'=>'Order Amount',
            'fr'=>'',
            'hi'=>'ऑर्डर करने की राशि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_action'=>[
            'en'=>'Action',
            'fr'=>'',
            'hi'=>'कार्य',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_order_details'=>[
            'en'=>'Order Details',
            'fr'=>'',
            'hi'=>'ऑर्डर का विवरण',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_datetime'=>[
            'en'=>'Datetime',
            'fr'=>'',
            'hi'=>'दिनांक और समय',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_orderitem_qty'=>[
            'en'=>'Order Items & Quantity',
            'fr'=>'',
            'hi'=>'ऑर्डर आइटम और मात्रा',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_stock'=>[
            'en'=>'Stock',
            'fr'=>'',
            'hi'=>'भण्डार',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_product_stocks'=>[
            'en'=>'Product Stocks',
            'fr'=>'',
            'hi'=>'उत्पाद स्टॉक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_current_stocks'=>[
            'en'=>'Current Stocks',
            'fr'=>'',
            'hi'=>'वर्तमान स्टॉक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_product'=>[
            'en'=>'Product',
            'fr'=>'',
            'hi'=>'उत्पाद',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_unit'=>[
            'en'=>'Unit',
            'fr'=>'',
            'hi'=>'इकाई',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_site_page_title'=>[
            'en'=>'Site Page Title',
            'fr'=>'',
            'hi'=>'साइट पेज शीर्षक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_site_lang'=>[
            'en'=>'Site Language',
            'fr'=>'',
            'hi'=>'साइट की भाषा',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_hotel_name'=>[
            'en'=>'Hotel Name',
            'fr'=>'',
            'hi'=>'होटल का नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_hotel_tagline'=>[
            'en'=>'Hotel Tagline',
            'fr'=>'',
            'hi'=>'होटल टैगलाइन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_hotel_email'=>[
            'en'=>'Hotel Email',
            'fr'=>'',
            'hi'=>'होटल ईमेल',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_hotel_phone'=>[
            'en'=>'Hotel Phone',
            'fr'=>'',
            'hi'=>'होटल फोन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_hotel_mobile'=>[
            'en'=>'Hotel Mobile',
            'fr'=>'',
            'hi'=>'होटल मोबाइल',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_hotel_website'=>[
            'en'=>'Hotel Website',
            'fr'=>'',
            'hi'=>'होटल की वेबसाइट',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_hotel_address'=>[
            'en'=>'Hotel Address',
            'fr'=>'',
            'hi'=>'होटल का पता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_gstin'=>[
            'en'=>'GSTIN',
            'fr'=>'',
            'hi'=>'',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_room_rent_gst'=>[
            'en'=>'Room Rent GST',
            'fr'=>'',
            'hi'=>'कमरे का किराया जी.एस.टी.',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_food_gst'=>[
            'en'=>'Food GST',
            'fr'=>'',
            'hi'=>'खाद्य जी.एस.टी.',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_gst'=>[
            'en'=>'GST',
            'fr'=>'',
            'hi'=>'जी.एस.टी.',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_sgst'=>[
            'en'=>'SGST',
            'fr'=>'',
            'hi'=>'एस.जी.एस.टी',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_cgst'=>[
            'en'=>'CGST',
            'fr'=>'',
            'hi'=>'सी.जी.एस.टी',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_gst_apply'=>[
            'en'=>'GST Apply',
            'fr'=>'',
            'hi'=>'जीएसटी लागू',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_category_name'=>[
            'en'=>'Category Name',
            'fr'=>'',
            'hi'=>'श्रेणी नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_status'=>[
            'en'=>'Status',
            'fr'=>'',
            'hi'=>'स्थिति',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_maintinance'=>[
            'en'=>'R&M Issue',
            'fr'=>'',
            'hi'=>'स्थिति',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_category'=>[
            'en'=>'Category',
            'fr'=>'',
            'hi'=>'श्रेणी',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_item_name'=>[
            'en'=>'Item Name',
            'fr'=>'',
            'hi'=>'वस्तु का नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_price'=>[
            'en'=>'Price',
            'fr'=>'',
            'hi'=>'कीमत',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_desc'=>[
            'en'=>'Description',
            'fr'=>'',
            'hi'=>'विवरण',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_invoice'=>[
            'en'=>'Invoice',
            'fr'=>'',
            'hi'=>'रसीद',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_name'=>[
            'en'=>'Name',
            'fr'=>'',
            'hi'=>'नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_fullname'=>[
            'en'=>'Full name',
            'fr'=>'',
            'hi'=>'पूरा नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_father_name'=>[
            'en'=>'Father Name',
            'fr'=>'',
            'hi'=>'',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_mobile_num'=>[
            'en'=>'Mobile No.',
            'fr'=>'',
            'hi'=>'मोबाइल नंबर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_gst_num'=>[
            'en'=>'GST No.',
            'fr'=>'',
            'hi'=>'मोबाइल नंबर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_concern_person'=>[
            'en'=>'Concerned Person.',
            'fr'=>'',
            'hi'=>'मोबाइल नंबर',
            'rm'=>'',
            'es'=>'',
        ],

        'txt_city'=>[
            'en'=>'City',
            'fr'=>'',
            'hi'=>'शहर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_state'=>[
            'en'=>'State',
            'fr'=>'',
            'hi'=>'राज्य',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_country'=>[
            'en'=>'Country',
            'fr'=>'',
            'hi'=>'देश',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_nationality'=>[
            'en'=>'Nationality',
            'fr'=>'',
            'hi'=>'राष्ट्रीयता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_ph'=>[
            'en'=>'Ph',
            'fr'=>'',
            'hi'=>'',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_mob'=>[
            'en'=>'M',
            'fr'=>'',
            'hi'=>'',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_num'=>[
            'en'=>'No.',
            'fr'=>'',
            'hi'=>'',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_dated'=>[
            'en'=>'Dated',
            'fr'=>'',
            'hi'=>'दिनांक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_date'=>[
            'en'=>'Date',
            'fr'=>'',
            'hi'=>'दिनांक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_cust_name'=>[
            'en'=>'Customer Name',
            'fr'=>'',
            'hi'=>'ग्राहक का नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_address'=>[
            'en'=>'Address',
            'fr'=>'',
            'hi'=>'पता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_waiter'=>[
            'en'=>'Waiter',
            'fr'=>'',
            'hi'=>'वेटर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_item_details'=>[
            'en'=>'Item Details',
            'fr'=>'',
            'hi'=>'आइटम विवरण',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_item_qty'=>[
            'en'=>'Item Qty',
            'fr'=>'',
            'hi'=>'आइटम मात्रा',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_item_price'=>[
            'en'=>'Item Price',
            'fr'=>'',
            'hi'=>'सामान की क़ीमत',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_amount'=>[
            'en'=>'Amount',
            'fr'=>'',
            'hi'=>'रकम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_no_orders'=>[
            'en'=>'No Orders',
            'fr'=>'',
            'hi'=>'कोई ऑर्डर नहीं',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_discount'=>[
            'en'=>'Discount',
            'fr'=>'',
            'hi'=>'छूट',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_total_amount'=>[
            'en'=>'Total Amount',
            'fr'=>'',
            'hi'=>'कुल रकम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_subtotal'=>[
            'en'=>'Subtotal',
            'fr'=>'',
            'hi'=>'उपयोग',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_total'=>[
            'en'=>'Total',
            'fr'=>'',
            'hi'=>'संपूर्ण',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_grand_total'=>[
            'en'=>'Grand Total',
            'fr'=>'',
            'hi'=>'कुल योग',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_amount_words'=>[
            'en'=>'Amount in Words',
            'fr'=>'',
            'hi'=>'राशि शब्दों में',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_customer_sign'=>[
            'en'=>'Customer Signature',
            'fr'=>'',
            'hi'=>'ग्राहक के हस्ताक्षर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_manager_sign'=>[
            'en'=>'Manager Signature',
            'fr'=>'',
            'hi'=>'प्रबंधक के हस्ताक्षर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_num_of_persons'=>[
            'en'=>'No. of Persons',
            'fr'=>'',
            'hi'=>'व्यक्तियों की संख्या',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_waiter_name'=>[
            'en'=>'Waiter Name',
            'fr'=>'',
            'hi'=>'वेटर का नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_payment_mode'=>[
            'en'=>'Payment Mode',
            'fr'=>'',
            'hi'=>'भुगतान का प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_inv_applicable'=>[
            'en'=>'Invoice Applicable',
            'fr'=>'',
            'hi'=>'चालान लागू',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_website'=>[
            'en'=>'Website',
            'fr'=>'',
            'hi'=>'वेबसाइट',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_bill_to'=>[
            'en'=>'Bill To',
            'fr'=>'',
            'hi'=>'बिल प्राप्तकर्ता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_unit'=>[
            'en'=>'Unit',
            'fr'=>'',
            'hi'=>'इकाई',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_orderd_items'=>[
            'en'=>'Ordered Items',
            'fr'=>'',
            'hi'=>'आइटम ऑर्डर किए गए',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_token_num'=>[
            'en'=>'Token No.',
            'fr'=>'',
            'hi'=>'टोकन नंबर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_type'=>[
            'en'=>'Type',
            'fr'=>'',
            'hi'=>'प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_date_from'=>[
            'en'=>'Date From',
            'fr'=>'',
            'hi'=>'तारीख से',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_date_to'=>[
            'en'=>'Date To',
            'fr'=>'',
            'hi'=>'की तारीख',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_order_by'=>[
            'en'=>'Order By',
            'fr'=>'',
            'hi'=>'द्वारा ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_inv_num'=>[
            'en'=>'Invoice No.',
            'fr'=>'',
            'hi'=>'रसीद संख्या',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_tbl_room_num'=>[
            'en'=>'Table/Room No.',
            'fr'=>'',
            'hi'=>'टेबल / कमरा नं',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_order_date'=>[
            'en'=>'Order Date',
            'fr'=>'',
            'hi'=>'ऑर्डर की तारीख',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_pay_date'=>[
            'en'=>'Pay Date',
            'fr'=>'',
            'hi'=>'भुगतान की तिथि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_order_list'=>[
            'en'=>'Order List',
            'fr'=>'',
            'hi'=>'ऑर्डर सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_room_order'=>[
            'en'=>'Room Order',
            'fr'=>'',
            'hi'=>'कक्ष ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_tbl_order'=>[
            'en'=>'Table Order',
            'fr'=>'',
            'hi'=>'टेबल ऑर्डर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_curr_stock'=>[
            'en'=>'Current Stock',
            'fr'=>'',
            'hi'=>'वर्तमान स्टॉक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_product_name'=>[
            'en'=>'Product Name',
            'fr'=>'',
            'hi'=>'उत्पाद का नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_product'=>[
            'en'=>'Product',
            'fr'=>'',
            'hi'=>'उत्पाद',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_qty'=>[
            'en'=>'Quantity',
            'fr'=>'',
            'hi'=>'मात्रा',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_currency'=>[
            'en'=>'Currency',
            'fr'=>'',
            'hi'=>'मुद्रा',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_currency_symbol'=>[
            'en'=>'Currency Symbol',
            'fr'=>'',
            'hi'=>'मुद्रा चिन्ह',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_api_url'=>[
            'en'=>'Api URL',
            'fr'=>'',
            'hi'=>'एपीआई URL',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_api_username'=>[
            'en'=>'Username',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_api_senderid'=>[
            'en'=>'Sender Id',
            'fr'=>'',
            'hi'=>'प्रेषक आईडी',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_api_key'=>[
            'en'=>'Api Key',
            'fr'=>'',
            'hi'=>'एपीआई Key',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_api_active'=>[
            'en'=>'Api Active',
            'fr'=>'',
            'hi'=>'एपीआई सक्रिय',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_email'=>[
            'en'=>'Email',
            'fr'=>'',
            'hi'=>'ईमेल',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_permission'=>[
            'en'=>'Permission',
            'fr'=>'',
            'hi'=>'अनुमति',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_superadmin'=>[
            'en'=>'Super Admin',
            'fr'=>'',
            'hi'=>'सुपर एडमिन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_admin'=>[
            'en'=>'Admin',
            'fr'=>'',
            'hi'=>'एडमिन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_receptionist'=>[
            'en'=>'Receptionist',
            'fr'=>'',
            'hi'=>'रिसेप्शनिस्ट',
            'rm'=>'',
            'es'=>'',
        ],
        'heading_guest_type'=>[
            'en'=>'Guest Type',
            'fr'=>'',
            'hi'=>'अतिथि प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_advance_payment'=>[
            'en'=>'Advance Payment',
            'fr'=>'',
            'hi'=>'अग्रिम भुगतान',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_booking_payment'=>[
            'en'=>'Booking Payment',
            'fr'=>'',
            'hi'=>'अग्रिम भुगतान',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_age'=>[
            'en'=>'D.O.B',
            'fr'=>'',
            'hi'=>'आयु',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_gender'=>[
            'en'=>'Gender',
            'fr'=>'',
            'hi'=>'लिंग',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_type_id'=>[
            'en'=>'Type of ID',
            'fr'=>'',
            'hi'=>'आईडी का प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_id_number'=>[
            'en'=>'ID No.',
            'fr'=>'',
            'hi'=>'पहचान संख्या',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_upload_idcard'=>[
            'en'=>'Upload ID Card',
            'fr'=>'',
            'hi'=>'आईडी कार्ड अपलोड करें',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_multiple'=>[
            'en'=>'Multiple',
            'fr'=>'',
            'hi'=>'विभिन्न',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_adults'=>[
            'en'=>'Adults',
            'fr'=>'',
            'hi'=>'वयस्क',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_kids'=>[
            'en'=>'Kids(Above 5)',
            'fr'=>'',
            'hi'=>'बच्चे',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_booked_by'=>[
            'en'=>'Booked By',
            'fr'=>'',
            'hi'=>'द्वारा बुक किया',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_vehicle_number'=>[
            'en'=>'Vehicle Number',
            'fr'=>'',
            'hi'=>'गाडी नंबर',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_referred_by'=>[
            'en'=>'Referred By',
            'fr'=>'',
            'hi'=>'द्वारा उल्लिखित',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_referred_by_name'=>[
            'en'=>'Referred By ',
            'fr'=>'',
            'hi'=>'नाम से संदर्भित',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_reason_of_visit'=>[
            'en'=>'Reason of Visit/Stay',
            'fr'=>'',
            'hi'=>'यात्रा/रहने का कारण',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_remark_amount'=>[
            'en'=>'Remark Amount',
            'fr'=>'',
            'hi'=>'रिमार्क राशि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_remark'=>[
            'en'=>'Remark',
            'fr'=>'',
            'hi'=>'टिप्पणी',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_select'=>[
            'en'=>'Select',
            'fr'=>'',
            'hi'=>'चयन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_select_rooms'=>[
            'en'=>'Select Rooms',
            'fr'=>'',
            'hi'=>'कमरे का चयन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_reserved_rooms'=>[
            'en'=>'Reserved Rooms',
            'fr'=>'',
            'hi'=>'कमरे का चयन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_room_type'=>[
            'en'=>'Room Type',
            'fr'=>'',
            'hi'=>'कक्ष के प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_duration_of_stay'=>[
            'en'=>'Duration of Stay',
            'fr'=>'',
            'hi'=>'रहने की अवधि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_checkout'=>[
            'en'=>'Check Out',
            'fr'=>'',
            'hi'=>'चेक आउट',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_checkin'=>[
            'en'=>'Check In',
            'fr'=>'',
            'hi'=>'चेक इन',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_guest'=>[
            'en'=>'Guest',
            'fr'=>'',
            'hi'=>'अतिथि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_new_guest'=>[
            'en'=>'New Guest',
            'fr'=>'',
            'hi'=>'नए मेहमान',
            'rm'=>'',
            'es'=>'',
        ],
     'txt_inclusive_tax'=>[
            'en'=>'Inclusive Tax',
            'fr'=>'',
            'hi'=>'नए मेहमान',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_existing_guest'=>[
            'en'=>'Existing Guest',
            'fr'=>'',
            'hi'=>'मौजूदा अतिथि',
            'rm'=>'',
            'es'=>'',
        ],
         'txt_exclusive_tax'=>[
            'en'=>'Exclusive Tax',
            'fr'=>'',
            'hi'=>'मौजूदा अतिथि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_guest_name'=>[
            'en'=>'Guest Name',
            'fr'=>'',
            'hi'=>'मेहमान का नाम',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_room'=>[
            'en'=>'Room',
            'fr'=>'',
            'hi'=>'कक्ष',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_guest'=>[
            'en'=>'Guest',
            'fr'=>'',
            'hi'=>'मेहमान',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_final_amount'=>[
            'en'=>'Final Amount',
            'fr'=>'',
            'hi'=>'अंतिम राशी',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_no_record'=>[
            'en'=>'No Records',
            'fr'=>'',
            'hi'=>'कोई रिकॉर्ड नहीं',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_food_orders'=>[
            'en'=>'Food Orders',
            'fr'=>'',
            'hi'=>'खाद्य आदेश',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_advance_amount'=>[
            'en'=>'Advance Amount',
            'fr'=>'',
            'hi'=>'अग्रिम राशि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_base_price'=>[
            'en'=>'Base Price',
            'fr'=>'',
            'hi'=>'आधार मूल्य',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_room_qty'=>[
            'en'=>'Room Qty',
            'fr'=>'',
            'hi'=>'कक्ष मात्रा',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_no_file'=>[
            'en'=>'No Files Uploaded',
            'fr'=>'',
            'hi'=>'कोई फ़ाइल अपलोड नहीं की गई',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_idcard'=>[
            'en'=>'Id Card',
            'fr'=>'',
            'hi'=>'आईडी कार्ड',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_idcard_uploaded'=>[
            'en'=>'Uploaded Id Cards',
            'fr'=>'',
            'hi'=>'अपलोड किए गए आईडी कार्ड',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_idcard_type'=>[
            'en'=>'ID Card Type',
            'fr'=>'',
            'hi'=>'आईडी कार्ड का प्रकार',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_idcard_num'=>[
            'en'=>'ID Card Number',
            'fr'=>'',
            'hi'=>'परिचय - पत्र संख्या',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_company_gst_num'=>[
            'en'=>'Company GST No.',
            'fr'=>'',
            'hi'=>'कंपनी जीएसटी नं.',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_persons'=>[
            'en'=>'Person`s',
            'fr'=>'',
            'hi'=>'व्यक्ति',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_checkin_from_date'=>[
            'en'=>'Check In Form Date',
            'fr'=>'',
            'hi'=>'चेक-इन फॉर्म की तारीख',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_checkout_from_date'=>[
            'en'=>'Check Out Form Date',
            'fr'=>'',
            'hi'=>'चेक-आउट फॉर्म की तारीख',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_years'=>[
            'en'=>'Years',
            'fr'=>'',
            'hi'=>'वर्ष',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_yes'=>[
            'en'=>'Yes',
            'fr'=>'Yes',
            'hi'=>'Yes',
            'rm'=>'Yes',
            'es'=>'Yes',
        ],
        'txt_no'=>[
            'en'=>'No',
            'fr'=>'No',
            'hi'=>'No',
            'rm'=>'No',
            'es'=>'No',
        ],
        'txt_uploaded_files'=>[
            'en'=>'Uploaded Files',
            'fr'=>'',
            'hi'=>'अपलोड की गई फाइलें',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_user'=>[
            'en'=>'User',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_corporate'=>[
            'en'=>'Corporate',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_ta'=>[
            'en'=>'TA',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_status'=>[
            'en'=>'Status',
            'fr'=>'',
            'hi'=>'स्थिति',
            'rm'=>'',
            'es'=>'',
        ],
    'txt_action'=>[
            'en'=>'Action',
            'fr'=>'',
            'hi'=>'स्थिति',
            'rm'=>'',
            'es'=>'',
        ],
    'txt_switch'=>[
            'en'=>'Switch Room',
            'fr'=>'',
            'hi'=>'स्थिति',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_password'=>[
            'en'=>'Password',
            'fr'=>'',
            'hi'=>'पासवर्ड',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_password_new'=>[
            'en'=>'New Password',
            'fr'=>'',
            'hi'=>'नया पासवर्ड',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_password_conf'=>[
            'en'=>'Confirm Password',
            'fr'=>'',
            'hi'=>'पासवर्ड की पुष्टि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_user_role'=>[
            'en'=>'User Role',
            'fr'=>'',
            'hi'=>'',
            'rm'=>'उपयोगकर्ता भूमिका',
            'es'=>'',
        ],
        'txt_role'=>[
            'en'=>'Role',
            'fr'=>'',
            'hi'=>'भूमिका',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_description'=>[
            'en'=>'Description',
            'fr'=>'',
            'hi'=>'विवरण',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_amenities'=>[
            'en'=>'Amenities',
            'fr'=>'',
            'hi'=>'सुविधाएँ',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_list_amenities'=>[
            'en'=>'List Amenities',
            'fr'=>'',
            'hi'=>'सुविधाओं की सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_floor'=>[
            'en'=>'Floor',
            'fr'=>'',
            'hi'=>'मंज़िल',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_list_room'=>[
            'en'=>'List Rooms',
            'fr'=>'',
            'hi'=>'कमरों की सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_title'=>[
            'en'=>'Title',
            'fr'=>'',
            'hi'=>'शीर्षक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_short_code'=>[
            'en'=>'Short Code',
            'fr'=>'',
            'hi'=>'छोटा संकेत',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_adult_capacity'=>[
            'en'=>'Adult Capacity',
            'fr'=>'',
            'hi'=>'वयस्क क्षमता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_kids_capacity'=>[
            'en'=>'Kids Capacity',
            'fr'=>'',
            'hi'=>'बच्चों की क्षमता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_capacity'=>[
            'en'=>'Capacity',
            'fr'=>'',
            'hi'=>'क्षमता',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_by'=>[
            'en'=>'By',
            'fr'=>'',
            'hi'=>'द्वारा',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_customer'=>[
            'en'=>'Customer',
            'fr'=>'',
            'hi'=>'ग्राहक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_list_users'=>[
            'en'=>'List Users',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_list_corporates'=>[
            'en'=>'Corporates List',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_list_tas'=>[
            'en'=>'TA List ',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_list_ota'=>[
            'en'=>'OTA List ',
            'fr'=>'',
            'hi'=>'उपयोगकर्ता सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_list_customers'=>[
            'en'=>'List Customers',
            'fr'=>'',
            'hi'=>'ग्राहकों की सूची',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_invoice_tnc'=>[
            'en'=>'Invoice Term & Conditions',
            'fr'=>'',
            'hi'=>'रसीद नियम और शर्तें',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_attachment'=>[
            'en'=>'Attachment',
            'fr'=>'',
            'hi'=>'रसीदें',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_available'=>[
            'en'=>'Available',
            'fr'=>'',
            'hi'=>'उपलब्ध',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_booked'=>[
            'en'=>'Booked',
            'fr'=>'',
            'hi'=>'बुक किया',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_no_rooms'=>[
            'en'=>'No Rooms: ',
            'fr'=>'',
            'hi'=>'कोई कमरा नहीं',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_add_new_rooms'=>[
            'en'=>'Add New',
            'fr'=>'',
            'hi'=>'नया कक्ष जोड़ें',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_base_price_weekdays'=>[
            'en'=>'Base Price Weekdays',
            'fr'=>'',
            'hi'=>'आधार मूल्य कार्यदिवस
            ',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_start_date'=>[
            'en'=>'Start Date',
            'fr'=>'',
            'hi'=>'आरंभ करने की तिथि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_end_date'=>[
            'en'=>'End Date',
            'fr'=>'',
            'hi'=>'अंतिम तिथि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_date_price'=>[
            'en'=>'Date Price',
            'fr'=>'',
            'hi'=>'दिनांक मूल्य',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_base_price_weekends'=>[
            'en'=>'Base Price Weekend',
            'fr'=>'',
            'hi'=>'बेस प्राइस वीकेंड',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_booking_amount'=>[
            'en'=>'Booking Amount',
            'fr'=>'',
            'hi'=>'बुकिंग राशि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_amount_payable'=>[
            'en'=>'Amount Payable',
            'fr'=>'',
            'hi'=>'देय राशि',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_today_revenue'=>[
            'en'=>'Today Revenue',
            'fr'=>'',
            'hi'=>'आज का राजस्व',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_today_expenses'=>[
            'en'=>'Today Expenses',
            'fr'=>'',
            'hi'=>'आज का खर्च',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_room_occupancy'=>[
            'en'=>'Occupancy',
            'fr'=>'',
            'hi'=>'कमरे बुक',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_dob'=>[
            'en'=>'Date Of Birth',
            'fr'=>'',
            'hi'=>'जन्म की तारीख',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_continue_rooms'=>[
            'en'=>'Continue Rooms',
            'fr'=>'',
            'hi'=>'कमरे जारी रखें',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_same_day_checkout'=>[
            'en'=>'Same Day',
            'fr'=>'',
            'hi'=>'उसी दिन चेकइन/चेकआउट',
            'rm'=>'',
            'es'=>'',
        ],
        'txt_duration_of_stay'=>[
            'en'=>'Duration Of Stay',
            'fr'=>'',
            'hi'=>'रहने की अवधि',
            'rm'=>'',
            'es'=>'',
        ],
        'default_checkin_setting'=>[
            'en'=>'CheckIn Default Time',
            'fr'=>'',
            'hi'=>'चेक इन डिफ़ॉल्ट समय',
            'rm'=>'',
            'es'=>'',
        ],

    /* ----- /txt ----- */
];
